// ---------------Try and Catch ------------------------

try {
  console.log(a);
} catch (err) {
  console.log(err); //error is a object
}

console.log(5 + 67);

// ------------------------------------------------------
